// Actual Chrome interaction with a local fake API. No credentials or remote calls.
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {spawn}=require('node:child_process'),{setTimeout:sleep}=require('node:timers/promises'),F=require('../memory-flow.js');
(async()=>{
  const root=path.resolve(__dirname,'..'),sent=[],threadSent=[];let inflight=0,peak=0,mode='mixed',delay=100;
  const assets=['index.html','styles.css','memory-flow.css','relation-worker.js','memory-flow.js','memory-page.js','app.js','workspace.js','experiments.js','automation.js','classifier.js','lab.js','speech-windows.js','transcription.js','classifier-config.json','manual-test-example.json'];
  const batch=JSON.parse(JSON.stringify(F.example));batch.cases[6].expected_store_memory=false;batch.cases[6].expected_event_type=null;
  const server=http.createServer(async(req,res)=>{
    const json=(status,value)=>res.writeHead(status,{'Content-Type':'application/json'}).end(JSON.stringify(value));
    if(req.url==='/api/health')return json(200,{provider:'official',ready:true,engine:'jev-latest',message:'Local fixture'});
    if(req.url==='/api/relations'){
      let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);threadSent.push(body);
      const answers=Object.fromEntries(Object.entries(body.questions).map(([id,q])=>[id,{type:'choice',choice:'belongs',confidence:.2,probabilities:Object.fromEntries(Object.keys(q.criteria).map(key=>[key,key==='belongs'?.96:.02]))}]));
      return json(200,{request:body,response:{model:'fixture-not-model',answers},provider:'official',latencyMs:0});
    }
    if(req.url==='/api/classify'){
      let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);sent.push(body);peak=Math.max(peak,++inflight);await sleep(delay);inflight--;
      if(mode==='401')return json(401,{error:'Fixture quota',stopBatch:true});
      const c=F.example.cases.find(c=>c.current_utterance===body.state.current_utterance);assert.ok(c,'only fixture utterances');
      const isGate=!!body.questions.should_store_memory;
      if(mode==='mixed'&&c.id==='C06'&&!isGate)return json(500,{error:'Fixture type failure'});
      const store=mode==='mixed'&&c.id==='C03'?false:c.expected_store_memory;
      const keys=Object.keys(body.questions.event_type?.criteria || {});
      const type=mode==='dynamic'?keys[0]:mode==='mixed'&&c.id==='C04'?'other':c.expected_event_type;
      const probability=mode==='mixed'&&c.id==='C05'?.65:.94;
      const answers=isGate?{should_store_memory:{type:'noul',noul:store?probability:.03}}:{event_type:{type:'choice',choice:type,confidence:.1,probabilities:Object.fromEntries(keys.map(t=>[t,t===type?.94:.06/(keys.length-1)]))}};
      return json(200,{request:body,response:{model:'fixture-not-model',answers},provider:'official',latencyMs:delay});
    }
    const pathname=new URL(req.url,'http://localhost').pathname,name=pathname==='/'?'index.html':pathname.slice(1);
    if(!assets.includes(name))return res.writeHead(404).end();
    res.writeHead(200,{'Content-Type':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/html','Cache-Control':'no-store'}).end(await fs.readFile(path.join(root,name)));
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const profile=await fs.mkdtemp(path.join(os.tmpdir(),'norte-memory-test-'));
  const chrome=spawn('google-chrome',['--headless','--no-sandbox','--disable-gpu','--remote-debugging-port=0','--no-first-run','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});let socket;
  try{
    let port;for(let i=0;i<100;i++){try{port=(await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch(_){await sleep(100);}}assert.ok(port);
    const tabs=await fetch('http://127.0.0.1:'+port+'/json/list').then(r=>r.json());socket=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));
    let next=0;const pending=new Map(),errors=[];
    socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Page.javascriptDialogOpening'&&m.params.type==='beforeunload')call('Page.handleJavaScriptDialog',{accept:true}).catch(error=>errors.push(error.message));if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}});
    const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timed out: '+method+' '+JSON.stringify(params).slice(0,200)));},15000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});socket.send(JSON.stringify({id,method,params}));});
    const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
    const wait=async expression=>{for(let i=0;i<400;i++){if(await evaluate(expression))return;await sleep(50);}throw Error('Timed out: '+expression+'; errors: '+JSON.stringify(errors));};
    const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
    const setJSON=async value=>evaluate(`document.querySelector('#mfBatchJSON').value=${JSON.stringify(typeof value==='string'?value:JSON.stringify(value))}`);
    const pointer=async selector=>{const p=await evaluate(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});n.scrollIntoView({block:'nearest'});const r=n.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;return {x,y,ok:n.contains(document.elementFromPoint(x,y))};})()`);assert.ok(p.ok,'visible '+selector);await call('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',clickCount:1});};
    const shot=async name=>{const s=await call('Page.captureScreenshot',{format:'png'});await fs.writeFile('/tmp/norte-memory-'+name+'.png',Buffer.from(s.data,'base64'));};
    const snapshot=()=>evaluate('NorteMemoryPage.snapshot()');
    const outside=async()=>{await call('Input.dispatchMouseEvent',{type:'mousePressed',x:4,y:4,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:4,y:4,button:'left',clickCount:1});};
    const resize=async(selector,dx,dy,corner=false)=>{
      const p=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.left+${corner?'r.width-3':'r.width/2'},y:r.top+${corner?'r.height-3':'r.height/2'}};})()`);
      await call('Input.dispatchMouseEvent',{type:'mouseMoved',...p});await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',buttons:1,clickCount:1});
      await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x+dx,y:p.y+dy,button:'left',buttons:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x+dx,y:p.y+dy,button:'left',clickCount:1});await sleep(150);
    };
    await call('Runtime.enable');await call('Page.enable');await call('Page.addScriptToEvaluateOnNewDocument',{source:'window.confirm=()=>true;'});
    await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});
    await call('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/#manual'});
    await wait('window.NorteLab && NorteClassifier.isAvailable() && document.body.dataset.page==="manual"');
    await evaluate('document.querySelector("#manualState").value="Preserve manual draft";document.querySelector("#manualState").dispatchEvent(new Event("input"));');
    const oldArchive=await evaluate('NorteLab.snapshot()');
    await pointer('#memoryMode');await wait('document.body.dataset.page==="memory"');
    assert.equal((await snapshot()).batch,null);assert.equal(sent.length,0);assert.equal(await evaluate('document.querySelector("#sessionContent").hidden'),true);
    assert.equal((await snapshot()).library.versions.length,0,'opening the page creates no saved version');
    assert.equal(await evaluate('document.querySelector("#mfRun").disabled'),true);await shot('empty');
    await pointer('#mfPaste');await setJSON('{');await pointer('#mfLoad');assert.match(await evaluate('document.querySelector("#mfInputError").textContent'),/JSON inválido/);assert.equal(sent.length,0);
    await setJSON({...batch,cases:[{...batch.cases[1],expected_event_type:'other'}]});await click('#mfLoad');assert.match(await evaluate('document.querySelector("#mfInputError").textContent'),/null/);
    await outside();await pointer('[data-mf-confirm="cancel"]');assert.equal(await evaluate('document.querySelector("#mfInputDialog").open'),true);
    await setJSON(batch);await outside();await pointer('[data-mf-confirm="save"]');await wait('!document.querySelector("#mfInputDialog").open');
    assert.equal((await snapshot()).library.tests.length,0,'applying a JSON popup does not archive a test');
    assert.equal(await evaluate('document.querySelectorAll("#mfChunks [data-chunk]").length'),9);assert.equal(sent.length,0);await shot('loaded');
    assert.equal(await evaluate('document.querySelectorAll("[data-collapse][aria-expanded=false]").length'),9,'category/Ignore queues start collapsed');
    for(const key of ['raw_window','meeting_events','relation_events','thread_context','meeting_threads','meeting_relations']) {
      assert.equal(await evaluate(`document.querySelector('[data-stream-collapse="stream:${key}"]').getAttribute('aria-expanded')`),'false',key+' starts collapsed');
    }
    await click('[data-stream-collapse="stream:raw_window"]');await click('[data-stream-collapse="stream:meeting_events"]');
    assert.equal(await evaluate('document.querySelector("#mfGraphRawQueue").hidden'),false);
    assert.equal(await evaluate('document.querySelector("#mfGraphEventsQueue").hidden'),false);
    assert.equal(await evaluate('document.querySelectorAll("#mfScene [data-connection^=memory]").length'),8,'every type feeds meeting_events');
    await click('#mfCollapseAll');await click('#mfFit');
    await evaluate(`window.graphCounts=[0];window.graphObserver=new MutationObserver(()=>{const count=document.querySelectorAll('#mfGraphEventsQueue [data-record]').length;if(count!==graphCounts.at(-1))graphCounts.push(count);});graphObserver.observe(document.querySelector('#mfGraphEventsQueue'),{childList:true,subtree:true});`);
    await pointer('#mfRun');await wait('NorteMemoryPage.isRunning() && NorteMemoryPage.snapshot().run.records.length===1');
    assert.deepEqual((await snapshot()).raw_window.map(c=>c.chunk_id),['C01']);
    assert.deepEqual((await snapshot()).meeting_events,[],'receipt precedes the filter and type results');
    assert.deepEqual(await evaluate('[...document.querySelectorAll("#mfRawWindow [data-memory-chunk]")].map(n=>n.dataset.memoryChunk)'),['C01']);
    assert.deepEqual(await evaluate('[...document.querySelectorAll("#mfGraphRawQueue [data-record]")].map(n=>n.dataset.record)'),['C01']);
    assert.equal(await evaluate('document.querySelectorAll("#mfGraphEventsQueue [data-record]").length'),0,'raw arrival precedes memory classification on the map');
    await evaluate('window.firstRawGraphItem=document.querySelector("#mfGraphRawQueue [data-record]");');
    assert.equal(await evaluate('JSON.parse(localStorage.getItem("norte.meeting-memory.v1")).run.raw_window[0].chunk_id'),'C01');
    await wait('NorteMemoryPage.snapshot().run.records.length >= 2');
    await pointer('[data-chunk="C01"]');assert.equal((await snapshot()).follow,false);
    assert.equal(await evaluate('document.querySelector("#manualMode").disabled'),true);
    await evaluate('location.hash="#manual"');await wait('location.hash==="#memoria"');assert.equal(await evaluate('document.body.dataset.page'),'memory');
    await wait('NorteMemoryPage.snapshot().run.records.length >= 4');assert.equal((await snapshot()).selected,'C01','inspection is not hijacked by the running loop');
    assert.ok(await evaluate('JSON.stringify([...document.querySelectorAll("#mfGraphRawQueue [data-record]")].map(n=>n.dataset.record))===JSON.stringify(NorteMemoryPage.snapshot().run.records.slice(-Number(document.querySelector("#mfGraphRawCount").textContent.split("/")[1])).map(r=>r.id))'),'live raw FIFO includes ignored and in-flight arrivals');
    await evaluate('document.querySelector(`[data-chunk="${NorteMemoryPage.snapshot().run.records.at(-1).id}"]`).click()');assert.equal((await snapshot()).follow,true);
    await wait('!NorteMemoryPage.isRunning()');const s=await snapshot();assert.equal(s.run.status,'done');assert.equal(peak,1);assert.equal(sent.length,16);
    assert.equal(s.run.records[2].result.verdict,'fail');assert.equal(s.run.records[3].result.verdict,'fail');assert.equal(s.run.records[4].result.verdict,'warning');assert.equal(s.run.records[5].status,'error');assert.equal(s.run.records[6].result.typeMatches,null);
    assert.deepEqual(s.queues.ignored.map(x=>x.id),['C02','C03']);assert.deepEqual(s.queues.memory.observation.map(x=>x.id),['C01','C09']);assert.deepEqual(s.queues.memory.other.map(x=>x.id),['C04']);assert.deepEqual(s.queues.memory.requirement.map(x=>x.id),['C08']);assert.equal(s.queues.memory.action_item[0].id,'C07');assert.equal(s.queues.memory.decision.length,0);
    assert.equal(s.library.tests.length,0,'executing does not save a test');assert.equal(s.library.versions.length,0,'executing does not save questions');
    assert.deepEqual(s.meeting_events.map(e=>e.chunk_id),['C01','C04','C05','C07','C08','C09']);
    assert.deepEqual(s.meeting_events.map(e=>e.event_id),['E001','E002','E003','E004','E005','E006']);
    assert.ok(s.meeting_events.every(e=>e.status==='active'),'actual fixture types determine the initial status, including a misclassified proposal');
    const rawLimit=F.exportResults({run:s.run}).configuration.raw_window_limit;
    assert.equal(rawLimit,15,'new runs use the current memory schema');
    assert.deepEqual(s.raw_window.map(c=>c.chunk_id),s.run.records.slice(-rawLimit).map(record=>record.id),'the configured raw FIFO includes ignored, failed and accepted arrivals');
    assert.equal(await evaluate('document.querySelector("#mfGraphRawCount").textContent'),s.raw_window.length+'/'+rawLimit);
    assert.equal(s.run.thread_worker.status,'done');assert.ok(s.run.thread_worker.jobs.every(job=>job.status==='done'),JSON.stringify(s.run.thread_worker.jobs.filter(job=>job.status!=='done')));
    assert.deepEqual(s.meeting_threads.map(thread=>thread.thread_id),['T001']);
    assert.ok(s.meeting_events.every(event=>event.thread_id==='T001'&&event.thread_assignment_state==='assigned'),'mock thread results are reflected in retained memory');
    assert.ok(threadSent.length>0);assert.ok(threadSent.every(request=>!JSON.stringify(request).includes('expected_')));
    assert.deepEqual(await evaluate('[...document.querySelectorAll("#mfGraphEventsQueue [data-record]")].map(n=>n.dataset.record)'),s.meeting_events.map(e=>e.chunk_id));
    assert.deepEqual(await evaluate('[...document.querySelectorAll("#mfGraphRawQueue [data-record]")].map(n=>n.dataset.record)'),s.raw_window.map(e=>e.chunk_id));
    assert.equal(await evaluate('firstRawGraphItem.isConnected'),true,'arrivals inside the configured window retain their existing DOM');
    assert.deepEqual(await evaluate('graphObserver.disconnect();graphCounts'),[0,1,2,3,4,5,6],'events appear one by one, never as a final-only batch');
    assert.equal(s.run.records[4].result.storeProbability,.65);assert.equal(s.run.records[4].result.typeProbability,.94,'audit confidence is selected-class probability, not API confidence');
    assert.ok(s.meeting_events.every(event=>!Object.hasOwn(event,'store_confidence')&&!Object.hasOwn(event,'type_confidence')),'memory schema keeps classification confidence in the audit record');
    assert.match(s.meeting_events[5].timestamp,/^00:00:\d{2}$/);assert.notEqual(s.meeting_events[5].timestamp,'00:00:00');
    assert.deepEqual(await evaluate('JSON.parse(localStorage.getItem("norte.meeting-memory.v1")).run.meeting_events'),s.meeting_events);
    assert.equal(await evaluate('document.querySelectorAll("#mfMeetingEvents [data-event-id]").length'),6);
    assert.equal(await evaluate('document.querySelectorAll("#mfRawWindow [data-memory-chunk]").length'),s.raw_window.length);
    assert.ok(await evaluate('[...document.querySelectorAll(".mf-memory-detail")].every(n=>n.hidden)'), 'memory rows start compact');
    assert.ok(await evaluate('[...document.querySelectorAll(".mf-memory-item")].every(n=>n.offsetHeight<=55)'), 'memory rows fit a compact list');
    await pointer('#mfMeetingEvents [data-event-id="E002"]');await wait('document.querySelector("[data-edge=other]").dataset.tone==="fail"');
    assert.equal(await evaluate('document.querySelector("#mfMeetingEvents [data-event-id=E002]").getAttribute("aria-expanded")'),'true');
    assert.match(await evaluate('document.querySelector("#mfMeetingEvents [data-event-id=E002]").nextElementSibling.textContent'),/current_utterance.*event_idE002.*chunk_idC04.*timestamp.*typeother.*statusactive.*thread_idT001.*thread_assignment_stateassigned/s);
    await pointer('#mfMeetingEvents [data-event-id="E002"]');
    assert.equal(await evaluate('document.querySelector("#mfMeetingEvents [data-event-id=E002]").nextElementSibling.hidden'),true,'same row collapses again without changing selection');
    assert.equal((await snapshot()).selected,'C04');assert.equal(await evaluate('document.querySelector("#mfMeetingEvents .is-selected").dataset.eventId'),'E002');
    assert.equal(await evaluate(`document.querySelector('[data-connection="memory:other"]').dataset.tone`),'fail');
    const assertChunkHighlight=async(id,tone)=>{
      assert.ok(await evaluate(`['mfNodeChunk','mfNodeMeetingEvents'].every(id=>document.getElementById(id).dataset.tone==='')`),'shared memory containers always stay neutral');
      assert.ok(await evaluate(`[...document.querySelectorAll('#mfScene [data-record]')].every(n=>n.dataset.tone===(n.dataset.record===${JSON.stringify(id)}?${JSON.stringify(tone)}:''))`),'only the selected chunk has verdict coloring inside map queues');
      assert.ok(await evaluate(`[...document.querySelectorAll('#mfScene [data-record]:not(.is-selected)')].every(n=>getComputedStyle(n).backgroundColor==='rgb(6, 24, 39)')`),'unselected items do not inherit a green/red/amber background');
      assert.ok(await evaluate(`['mfNodeChunk','mfNodeMeetingEvents'].every(id=>getComputedStyle(document.getElementById(id)).backgroundColor==='rgb(8, 28, 48)')`),'entire raw and memory lists keep their neutral background');
    };
    await assertChunkHighlight('C04','fail');
    assert.equal(await evaluate('document.querySelector("#mfRawWindow .is-selected").dataset.memoryChunk'),'C04','an earlier chunk still inside the configured window stays synchronized');
    await pointer('#mfRawWindow [data-memory-chunk="C06"]');assert.equal((await snapshot()).selected,'C06');
    assert.equal(await evaluate('document.querySelectorAll("#mfMeetingEvents .is-selected").length'),0,'a type error has no memory event to highlight');
    await pointer('[data-chunk="C01"]');assert.equal(await evaluate('document.querySelector("#mfMeetingEvents .is-selected").dataset.eventId'),'E001');
    assert.equal(await evaluate('document.querySelector("#mfRawSelection").textContent'),'','retained chunks are not reported as evicted');
    assert.equal(await evaluate('document.querySelector("#mfGraphEventsQueue .is-selected").dataset.record'),'C01');
    assert.equal(await evaluate('document.querySelector("#mfGraphRawQueue .is-selected").dataset.record'),'C01','retained selection is shared by raw and stored graph queues');
    assert.deepEqual((await snapshot()).raw_window,s.raw_window,'inspection never changes arrival order');
    await assertChunkHighlight('C01','pass');
    const memoryBeforeInspect=JSON.stringify((await snapshot()).meeting_events);await pointer('#mfEventsToggle');assert.equal(await evaluate('document.querySelector("#mfMeetingEvents").hidden'),true);
    await pointer('#mfEventsToggle');await pointer('#mfRawToggle');assert.equal(await evaluate('document.querySelector("#mfRawWindow").hidden'),true);await pointer('#mfRawToggle');
    assert.equal(JSON.stringify((await snapshot()).meeting_events),memoryBeforeInspect,'collapsing/selection does not rewrite memory');
    await resize('#mfMemoryDivider',-35,0);
    assert.ok(await evaluate('JSON.parse(localStorage.getItem("norte.memory-ui.v1")).memoryWidth>=340'));
    assert.equal(await evaluate('document.querySelector("#mfRawDivider")'),null,'memory collections use one scroll container');
    assert.equal(await evaluate('getComputedStyle(document.querySelector("#mfMemories")).overflowY'),'auto');
    await evaluate('document.querySelector("#mfMemories").scrollTop=document.querySelector("#mfMemories").scrollHeight');
    assert.ok(await evaluate('document.querySelector("#mfMemories").scrollTop>0'),'the shared sidebar scroll reaches its raw collection');
    await pointer('[data-chunk="C09"]');await shot('meeting-events');
    await pointer('#mfSaveTest');assert.equal((await snapshot()).savedId,'T001');await pointer('#mfHistoryToggle');
    for(const req of sent){assert.deepEqual(Object.keys(req.state),['current_utterance']);assert.equal(Object.keys(req.questions).length,1);assert.ok(!JSON.stringify(req).includes('expected_'));}
    await pointer('[data-chunk="C03"]');await wait('document.querySelector("[data-edge=no]").dataset.tone==="fail"');assert.equal(await evaluate('document.querySelector("[data-edge=yes]").dataset.tone'),'');assert.match(await evaluate('document.querySelector("#mfInspector").textContent'),/Filtro divergente/);
    await pointer('[data-chunk="C04"]');await wait('document.querySelector("[data-edge=other]").dataset.tone==="fail"');assert.match(await evaluate('document.querySelector("#mfInspector").textContent'),/Tipo divergente/);await shot('type-failure');
    await pointer('[data-record="C02"]');await wait('document.querySelector("[data-edge=no]").dataset.tone==="pass"');assert.match(await evaluate('document.querySelector("#mfInspector").textContent'),/Não se aplica/);assert.doesNotMatch(await evaluate('document.querySelector("#mfInspector").textContent'),/Somente log Ignore/);assert.match(await evaluate('document.querySelector("#mfInspector").textContent'),/Input · current_utterance/);await shot('ignore');
    await pointer('[data-chunk="C09"]');await shot('memory');
    await wait('document.querySelector("#mfNode-other").getBoundingClientRect().bottom <= document.querySelector("#mfCanvas").getBoundingClientRect().bottom + 1');
    assert.ok(await evaluate('(()=>{const path=document.querySelector("[data-edge=observation]"),point=path.getPointAtLength(path.getTotalLength()),p=new DOMPoint(point.x,point.y).matrixTransform(path.getScreenCTM()),r=document.querySelector("#mfNode-observation").getBoundingClientRect();return Math.abs(p.x-r.left)<2 && Math.abs(p.y-r.top-r.height/2)<2})()'),'zoom keeps connectors aligned with actual nodes');
    const beforeZoom=await evaluate('document.querySelector("#mfScene").dataset.scale');await pointer('#mfZoomIn');assert.ok(Number(await evaluate('document.querySelector("#mfScene").dataset.scale'))>Number(beforeZoom));await pointer('#mfFit');
    await pointer('#mfQuestions');assert.equal(await evaluate('document.querySelector("#mfQuestionsDialog").open'),true);await click('#mfQuestionsDialog [data-mf-close]');
    assert.deepEqual(await evaluate('NorteLab.snapshot()'),oldArchive,'memory experiment leaves archive untouched');
    await pointer('#manualMode');assert.equal(await evaluate('document.querySelector("#manualState").value'),'Preserve manual draft');await pointer('#memoryMode');assert.equal((await snapshot()).run.records.length,9);
    await evaluate('window.beforeMemoryReload=true');
    await call('Page.reload');await wait('!window.beforeMemoryReload && window.NorteMemoryPage && document.body.dataset.page==="memory" && NorteClassifier.isAvailable()');assert.equal((await snapshot()).run.records.length,9);assert.equal(sent.length,16);assert.equal((await snapshot()).selected,'C09');
    await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(150);assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);await shot('mobile');
    await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});
    await click('#mfFit');await sleep(100);
    assert.equal(await evaluate('document.querySelector("#mfExample")'),null,'example action removed');
    assert.equal(await evaluate('document.querySelector("#mfTotals")'),null);
    assert.equal(await evaluate('document.querySelector(".mf-legend")'),null);
    assert.equal(await evaluate('document.querySelector("#mfFollow")'),null);
    assert.equal(await evaluate('getComputedStyle(document.querySelector("#providerStatus")).display'),'none');
    assert.equal(await evaluate('document.querySelector("#mfQuestions").textContent'),'Questões');
    assert.equal(await evaluate('document.querySelector("#mfSaveTest").textContent'),'Salvo');
    await evaluate('document.querySelector("#mfProgress [data-tone=pass]").focus()');
    assert.equal(await evaluate('document.querySelector("#mfVerdictTooltip").hidden'),false);
    assert.equal(await evaluate('document.querySelectorAll("#mfVerdictTooltip i").length'),3);await shot('verdict-tooltip');
    await evaluate('document.activeElement.blur()');assert.equal(await evaluate('document.querySelector("#mfVerdictTooltip").hidden'),true);
    const camera=()=>evaluate('(()=>{const n=document.querySelector("#mfCanvas"),r=n.getBoundingClientRect();return {x:r.left,y:r.top,w:r.width,h:r.height,panX:Number(n.dataset.panX),panY:Number(n.dataset.panY),scale:Number(document.querySelector("#mfScene").dataset.scale)};})()');
    const before=await camera(),point={x:before.x+30,y:before.y+30};
    const panTarget=await evaluate(`document.elementFromPoint(${point.x},${point.y})?.outerHTML.slice(0,160)`);
    await call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});
    await call('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});
    await wait('document.querySelector("#mfCanvas").classList.contains("is-dragging")');
    await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:point.x+80,y:point.y+40,buttons:1});
    await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:point.x+80,y:point.y+40,button:'left',clickCount:1});await sleep(100);
    const moved=await camera();assert.ok(Math.abs(moved.panX-before.panX-80)<2,JSON.stringify({before,moved,panTarget}));assert.ok(Math.abs(moved.panY-before.panY-40)<2);
    await call('Input.dispatchMouseEvent',{type:'mouseWheel',...point,deltaX:0,deltaY:-150});await sleep(100);
    const zoomed=await camera();assert.ok(zoomed.scale>moved.scale);assert.ok(Math.abs((30-moved.panX)/moved.scale-(30-zoomed.panX)/zoomed.scale)<2,'wheel zoom is anchored at cursor');
    await click('#mfFit');await sleep(100);
    const naturalHeight=await evaluate('document.querySelector("#mfScene").offsetHeight');await pointer('#mfCollapseAll');await sleep(100);
    assert.equal(await evaluate('document.querySelectorAll("[data-collapse][aria-expanded=false]").length'),9);
    assert.ok(await evaluate('document.querySelector("#mfScene").offsetHeight')<naturalHeight);
    await pointer('[data-collapse="type:observation"]');assert.equal(await evaluate('document.querySelector("#mfQueue-observation").hidden'),false);
    await click('#mfCollapseAll');await click('#mfCollapseAll');await click('#mfFit');
    await pointer('#mfHistoryToggle');assert.equal(await evaluate('document.querySelector("#mfHistory").hidden'),false);
    await shot('history');
    assert.equal((await snapshot()).library.tests.length,1,'only the explicitly saved run is archived');
    assert.match(await evaluate('document.querySelector("#mfTestRows tr").textContent'),/T001_B001/);
    assert.deepEqual(await evaluate('[...document.querySelectorAll("#mfTestRows [data-mf-export]")].map(button=>button.dataset.mfExport)'),['json','csv']);
    assert.equal(await evaluate('document.querySelector("#mfTestRows [data-delete-test]").dataset.deleteTest'),'T001');
    assert.equal(await evaluate('document.querySelector("#mfTestRows [data-select-test]").checked'),false,'history actions do not select or mutate a saved test automatically');
    const oldHistoryHeight=await evaluate('document.querySelector("#mfHistory").clientHeight');
    await resize('#mfHistoryDivider',0,-70);assert.ok(await evaluate('document.querySelector("#mfHistory").clientHeight')>oldHistoryHeight+40);
    await resize('#mfHistoryDivider',0,70);
    await resize('#mfInspectorDivider',0,-35);await resize('#mfSidebarDivider',30,0);
    const savedLayout=await evaluate('JSON.parse(localStorage.getItem("norte.memory-ui.v1"))');assert.ok(savedLayout.historyHeight&&savedLayout.inspectorHeight&&savedLayout.sidebarWidth);
    const originalRun=JSON.stringify((await snapshot()).library.tests[0].run);
    await pointer('#mfQuestions');assert.equal(await evaluate('document.querySelector("#mfQuestionsTitle").textContent'),'Questões');
    assert.equal(await evaluate('document.querySelector("#mfQuestionJSON").readOnly'),false,'saved questions are directly editable');
    assert.equal(await evaluate('document.querySelector("#mfQuestionId").textContent'),'Q001');
    assert.ok(await evaluate('document.querySelectorAll("#mfQuestionHighlight .json-key").length')>0,'question editor syntax colors');
    assert.equal(await evaluate('document.querySelector("#mfForkQuestions")'),null);assert.equal(await evaluate('document.querySelector("#mfCompareVersion")'),null);
    const oldQuestionWidth=await evaluate('document.querySelector("#mfQuestionsDialog").getBoundingClientRect().width');assert.ok(oldQuestionWidth>1000);
    await resize('#mfQuestionsDialog',-160,-100,true);
    const questionSize=await evaluate('JSON.parse(localStorage.getItem("norte.memory-ui.v1")).questionsSize');assert.ok(questionSize.width<oldQuestionWidth-50,'native question resize is saved');
    await outside();assert.equal(await evaluate('document.querySelector("#mfQuestionsDialog").open'),false,'clean popup closes on backdrop');
    await pointer('#mfQuestions');assert.ok(Math.abs(await evaluate('document.querySelector("#mfQuestionsDialog").getBoundingClientRect().width')-questionSize.width)<2);
    const changed=JSON.parse(await evaluate('document.querySelector("#mfQuestionJSON").value'));changed.should_store_memory.instructions+=' Retain useful project background.';
    await evaluate(`document.querySelector('#mfQuestionJSON').value=${JSON.stringify(JSON.stringify(changed,null,2))};document.querySelector('#mfQuestionJSON').dispatchEvent(new Event('input'));`);
    await sleep(1000);assert.equal((await snapshot()).questionVersion,'Q001');assert.equal((await snapshot()).library.versions.length,1,'typing does not save a version');
    await outside();await wait('document.querySelector("#mfConfirmDialog").open');await pointer('[data-mf-confirm="cancel"]');
    assert.equal(await evaluate('document.querySelector("#mfQuestionsDialog").open'),true,'continue editing keeps the popup');
    await outside();await wait('document.querySelector("#mfConfirmDialog").open');await pointer('[data-mf-confirm="save"]');
    await wait('NorteMemoryPage.snapshot().questionVersion==="Q002" && !document.querySelector("#mfQuestionsDialog").open');
    assert.equal((await snapshot()).library.tests.length,1,'saving questions does not save a test');
    await pointer('#mfQuestions');await shot('question-versions');
    await evaluate('document.querySelector("#mfQuestionJSON").value="";document.querySelector("#mfQuestionJSON").dispatchEvent(new Event("input"));');await sleep(900);
    assert.equal(await evaluate('document.querySelector("#runTest").disabled'),true); // hidden original test bench is untouched/empty
    assert.equal(await evaluate('document.querySelector("#mfRun").disabled'),true,'invalid/empty Questions cannot silently send old configuration');
    assert.equal((await snapshot()).library.versions.length,2,'invalid edit does not create a version');
    await pointer('#mfQuestionsDialog [data-mf-close]');
    await pointer('[data-mf-confirm="save"]');assert.equal(await evaluate('document.querySelector("#mfQuestionsDialog").open'),true,'invalid JSON cannot close by saving');
    assert.match(await evaluate('document.querySelector("#mfQuestionError").textContent'),/JSON incompleto/);
    assert.equal((await snapshot()).library.tests.length,1);
    await outside();await pointer('[data-mf-confirm="discard"]');await pointer('#mfQuestions');
    assert.deepEqual(JSON.parse(await evaluate('document.querySelector("#mfQuestionJSON").value')),changed,'discard restores the saved version');
    assert.equal((await snapshot()).library.versions.length,2,'identical questions reuse their version');
    await pointer('#mfQuestionsDialog [data-mf-close]');await pointer('#mfSaveTest');assert.equal((await snapshot()).savedId,'T002');
    assert.equal(JSON.stringify((await snapshot()).library.tests[0].run),originalRun,'editing questions never mutates a saved execution');
    await click('[data-chunk="C09"]');await evaluate('[...document.querySelectorAll("#mfInspector button")].find(b=>b.textContent==="Editar input").click()');
    await evaluate('document.querySelector("#mfUtteranceEdit").value="Discard this edit"');await outside();await pointer('[data-mf-confirm="discard"]');
    assert.notEqual((await snapshot()).batch.cases[8].current_utterance,'Discard this edit');
    await evaluate('[...document.querySelectorAll("#mfInspector button")].find(b=>b.textContent==="Editar input").click()');
    await evaluate('document.querySelector("#mfUtteranceEdit").value="An edited input, not a model analysis."');await pointer('#mfSaveUtterance');
    assert.equal((await snapshot()).savedId,null);assert.equal((await snapshot()).library.tests.length,2,'input editing does not save a test');
    assert.equal((await snapshot()).batch.cases[8].current_utterance,'An edited input, not a model analysis.');assert.notEqual((await snapshot()).library.tests[0].batch.cases[8].current_utterance,'An edited input, not a model analysis.');
    await pointer('#mfSaveTest');assert.equal((await snapshot()).savedId,'T003');
    await pointer('[data-saved-test="T001"] td:nth-child(2)');await wait('NorteMemoryPage.snapshot().savedId==="T001"');
    assert.equal((await snapshot()).questionVersion,'Q001');assert.equal((await snapshot()).run.records.length,9);
    const gateRow='#mfInspector .mf-answer[data-question="should_store_memory"]',typeRow='#mfInspector .mf-answer[data-question="event_type"]';
    assert.equal(await evaluate('document.querySelector("#mfDetailsDialog")'),null,'responses no longer use a popup');
    assert.equal(await evaluate('document.querySelectorAll("#mfInspector .mf-answer").length'),2);
    assert.equal(await evaluate('document.querySelectorAll("#mfInspector .mf-distribution-option").length'),10);
    await pointer(gateRow+' > summary');await wait('document.querySelector(".mf-main").classList.contains("has-expanded-answer")');
    assert.equal(await evaluate('document.querySelectorAll("dialog[open]").length'),0);
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' > summary')}).textContent`),/Resposta correta.*Esperado: true.*Confiança ≥ 80.0%.*Obtido: true.*94.0%/);
    assert.doesNotMatch(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' > summary')}).textContent`),/Noul|Choice/);
    assert.ok(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' > summary')}).offsetHeight<=58`),'collapsed question comparison uses two compact lines');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' [data-value="false"] .mf-probability-ring')}).style.getPropertyValue('--probability')`),String(1-.94));
    const booleanColors=await evaluate(`[...document.querySelectorAll('${gateRow} .mf-distribution-name')].map(n=>getComputedStyle(n).color)`);
    assert.notEqual(booleanColors[0],booleanColors[1],'false/true have distinct non-verdict colors');
    assert.ok(booleanColors.every(c=>!['rgb(90, 218, 178)','rgb(255, 132, 151)'].includes(c)));
    await shot('inline-noul');
    await pointer(gateRow+' > summary');await pointer(typeRow+' > summary');
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(typeRow)}).textContent`),/Confidence \(API\): 10.0%/);
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-distribution-option')}).dataset.value`),'observation');
    await pointer(typeRow+' [data-value="observation"] > summary');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' [data-value="observation"]')}).open`),true,'class criterion expands inline');
    await shot('inline-choice');
    await pointer(typeRow+' .mf-answer-raw > summary');
    assert.deepEqual(JSON.parse(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-answer-raw pre')}).textContent`)),(await snapshot()).run.records[0].typeOutput);
    await pointer(typeRow+' .mf-answer-raw > summary');
    await pointer('[data-chunk="C02"]');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow)}).open`),true,'expansion is preserved when selecting another input');
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' > summary')}).textContent`),/Não se aplica.*Não consultado/);
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-probability')}).textContent`),'—','a skipped call never invents a zero-probability response');
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' > summary')}).textContent`),/false.*97.0%/);
    await pointer('[data-chunk="C04"]');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-distribution-option')}).dataset.value`),'other','distribution is sorted by actual probabilities, not expected labels');
    assert.deepEqual(await evaluate(`[...document.querySelectorAll(${JSON.stringify(typeRow+' .mf-answer-value')})].map(n=>n.dataset.tone)`),['fail','fail'],'wrong answers are red independently of confidence');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-answer-confidence')}).dataset.tone`),'pass','a wrong answer can still meet the probability threshold');
    await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-answer-confidence')}).focus()`);
    assert.match(await evaluate('document.querySelector("#mfTooltipPass").textContent'),/mínimo.*não significa que a resposta esteja correta/);
    await evaluate('document.activeElement.blur()');
    await pointer('[data-chunk="C05"]');
    await assertChunkHighlight('C05','warning');
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' .mf-answer-verdict')}).textContent`),/Resposta correta/);
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' .mf-answer-confidence')}).dataset.tone`),'warning');
    assert.deepEqual(await evaluate(`[...document.querySelectorAll(${JSON.stringify(gateRow+' .mf-answer-value')})].map(n=>n.dataset.tone)`),['pass','pass'],'low confidence does not color a correct answer red');
    assert.equal(await evaluate(`document.querySelector(${JSON.stringify(gateRow+' .mf-answer-minimum')}).dataset.tone`),'warning');
    await shot('compact-confidence');
    await pointer('[data-chunk="C06"]');
    await assertChunkHighlight('C06','error');
    assert.match(await evaluate(`document.querySelector(${JSON.stringify(typeRow+' .mf-answer-verdict')}).textContent`),/Erro de execução/);
    await pointer('[data-chunk="C01"]');await pointer(typeRow+' > summary');
    assert.equal(JSON.stringify((await snapshot()).library.tests[0].run),originalRun,'inline inspection does not mutate stored results');
    await pointer('#mfClear');assert.equal((await snapshot()).batch,null);assert.equal((await snapshot()).library.tests.length,3,'clear keeps saved tests');assert.equal((await snapshot()).library.versions.length,2);
    assert.deepEqual((await snapshot()).meeting_events,[]);assert.deepEqual((await snapshot()).raw_window,[]);
    assert.equal(await evaluate('localStorage.getItem("norte.meeting-memory.v1")'),null,'clear removes only the active memory checkpoint');
    await evaluate('window.beforeMemoryReload=true');await call('Page.reload');await wait('!window.beforeMemoryReload && window.NorteMemoryPage && document.body.dataset.page==="memory" && NorteClassifier.isAvailable()');
    assert.equal((await snapshot()).library.tests.length,3,'test library survives reload with an empty workspace');assert.equal((await snapshot()).library.versions.length,2);
    assert.deepEqual(await evaluate('JSON.parse(localStorage.getItem("norte.memory-ui.v1")).questionsSize'),questionSize);
    await pointer('#mfQuestions');assert.ok(Math.abs(await evaluate('document.querySelector("#mfQuestionsDialog").getBoundingClientRect().width')-questionSize.width)<2,'resized popup survives reload');await outside();
    await click('#mfPaste');await setJSON({batch_id:'STOP',cases:[F.example.cases[0],F.example.cases[1]]});await click('#mfLoad');mode='ok';delay=700;
    await click('#mfRun');await wait('NorteMemoryPage.isRunning() && NorteMemoryPage.snapshot().run.records.length===1');await click('#mfStop');await wait('!NorteMemoryPage.isRunning()');
    assert.equal((await snapshot()).run.status,'stopped');assert.equal((await snapshot()).run.calls,1);assert.equal((await snapshot()).run.records[0].status,'interrupted');assert.equal((await snapshot()).queues.memory.observation.length,0);
    assert.deepEqual((await snapshot()).meeting_events,[]);assert.deepEqual((await snapshot()).raw_window.map(c=>c.chunk_id),['C01']);
    // A fresh tab/session can recover the active memory without creating a saved test.
    const interruptedMemory=await snapshot(),callsBeforeRecovery=sent.length;
    await evaluate('window.beforeMemoryReload=true;sessionStorage.removeItem("norte.memory-flow.v1")');
    await call('Page.reload');await wait('!window.beforeMemoryReload && window.NorteMemoryPage && NorteClassifier.isAvailable()');
    assert.deepEqual((await snapshot()).raw_window,interruptedMemory.raw_window);assert.equal((await snapshot()).run.status,'stopped');
    assert.equal((await snapshot()).library.tests.length,3);assert.equal(sent.length,callsBeforeRecovery,'restoration never repeats inference');
    mode='401';delay=1;await click('#mfRun');await wait('document.querySelector("#mfConfirmDialog").open');await pointer('[data-mf-confirm="discard"]');await wait('NorteMemoryPage.snapshot().run.records[0]?.status==="error" && !NorteMemoryPage.isRunning()');assert.equal((await snapshot()).run.calls,1);assert.equal((await snapshot()).run.records[0].status,'error');assert.equal((await snapshot()).run.status,'stopped');
    assert.equal((await snapshot()).library.tests.length,3,'neither interrupted nor failed runs are auto-saved');
    await pointer('#mfClear');await pointer('[data-mf-confirm="cancel"]');assert.ok((await snapshot()).batch,'cancel keeps unsaved results');
    await pointer('#mfClear');await pointer('[data-mf-confirm="save"]');await wait('NorteMemoryPage.snapshot().batch===null');
    assert.equal((await snapshot()).library.tests.length,4,'only explicit save in the replacement prompt archives the last result');
    assert.equal((await snapshot()).library.tests[3].run.records[0].status,'error');
    // Add a category through the actual editor, then run and reopen its snapshot.
    mode='dynamic';delay=1;
    await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
    const editQuestions=async questions=>evaluate(`(()=>{const e=document.querySelector('#mfQuestionJSON');e.value=${JSON.stringify(JSON.stringify(questions,null,2))};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    const saveQuestions=async questions=>{
      await pointer('#mfQuestions');await editQuestions(questions);await pointer('#mfSaveQuestions');
      await wait('document.querySelector("#mfQuestionStatus").textContent.includes("✓ Versão Q")');
      assert.match(await evaluate('document.querySelector("#mfQuestionStatus").textContent'),/^✓ Versão Q\d+ salva$/);
      assert.equal(await evaluate('document.querySelector("#mfSaveQuestions").textContent'),'Salvo');
      assert.equal(await evaluate('document.querySelector("#mfQuestionError").textContent'),'');await shot('category-saved');await outside();
    };
    const dynamicQuestions=JSON.parse(JSON.stringify(F.questions));
    dynamicQuestions.event_type.criteria={constraint:'An explicit project constraint.',...dynamicQuestions.event_type.criteria};
    await saveQuestions(dynamicQuestions);
    assert.deepEqual(await evaluate('[...document.querySelectorAll(".mf-destination")].map(n=>n.dataset.category)'),Object.keys(dynamicQuestions.event_type.criteria));
    assert.equal((await snapshot()).library.tests.length,4,'editing categories does not autosave a test');
    assert.ok(Object.hasOwn((await snapshot()).queues.memory,'constraint'));
    const customBatch={batch_id:'CUSTOM',cases:[F.example.cases[0],F.example.cases[8]].map(c=>({...c,expected_event_type:'constraint'}))};
    await click('#mfPaste');await setJSON(customBatch);await click('#mfLoad');await wait('!document.querySelector("#mfInputDialog").open');
    await click('#mfRun');await wait('NorteMemoryPage.snapshot().run?.status==="done" && !NorteMemoryPage.isRunning()');
    assert.equal((await snapshot()).run.calls,4);assert.deepEqual((await snapshot()).queues.memory.constraint.map(c=>c.id),['C01','C09']);
    assert.ok((await snapshot()).run.records.every(r=>r.result.verdict==='pass'));
    await wait('document.querySelector("[data-edge=constraint]")?.dataset.tone==="pass"');
    assert.equal(await evaluate('document.querySelector("#mfNode-constraint").dataset.tone'),'pass');
    await click('#mfInspector [data-question="event_type"] > summary');
    assert.equal(await evaluate('document.querySelectorAll("#mfInspector [data-question=event_type] .mf-distribution-option").length'),9);
    await click('#mfSaveTest');const customSaved=(await snapshot()).savedId;await shot('dynamic-result');
    await pointer('[data-saved-test="T001"]');assert.equal(await evaluate('document.querySelectorAll(".mf-destination").length'),8);assert.equal(await evaluate('document.querySelector("#mfNode-constraint")'),null);
    await pointer('[data-saved-test="'+customSaved+'"]');assert.equal(await evaluate('document.querySelectorAll(".mf-destination").length'),9);assert.equal((await snapshot()).queues.memory.constraint.length,2);
    for(const key of ['chunksHidden','inspectorHidden','memoriesHidden']) await pointer('.mf-panel-tools [data-panel-toggle="'+key+'"]');
    await evaluate('window.beforeMemoryReload=true');await call('Page.reload');await wait('!window.beforeMemoryReload && window.NorteMemoryPage && NorteClassifier.isAvailable()');
    for(const [key,id] of [['chunksHidden','mfSidebar'],['inspectorHidden','mfInspector'],['memoriesHidden','mfMemories']]) {
      assert.equal(await evaluate(`document.getElementById(${JSON.stringify(id)}).hidden`),true,'hidden panel persists after reload: '+id);
      assert.equal(await evaluate(`JSON.parse(localStorage.getItem('norte.memory-ui.v1'))[${JSON.stringify(key)}]`),true);
      await pointer('.mf-panel-tools [data-panel-toggle="'+key+'"]');
      assert.equal(await evaluate(`document.getElementById(${JSON.stringify(id)}).hidden`),false,'toolbar can restore panel: '+id);
    }
    assert.equal((await snapshot()).savedId,customSaved);assert.equal((await snapshot()).queues.memory.constraint.length,2);
    const persistedEvents=(await snapshot()).meeting_events;
    await evaluate('window.beforeMemoryReload=true;sessionStorage.removeItem("norte.memory-flow.v1")');await call('Page.reload');
    await wait('!window.beforeMemoryReload && window.NorteMemoryPage && NorteClassifier.isAvailable()');
    assert.deepEqual((await snapshot()).meeting_events,persistedEvents,'persistent events survive a fresh session with stable event IDs');
    assert.equal((await snapshot()).savedId,customSaved);
    // Category changes cannot silently rewrite an expected label or an old result.
    const reduced=JSON.parse(JSON.stringify(dynamicQuestions));reduced.event_type.criteria={ignore:'A retained memory category named ignore.',yes:'A category named yes.'};
    await saveQuestions(reduced);assert.equal(await evaluate('document.querySelectorAll(".mf-destination").length'),2);
    assert.match(await evaluate('document.querySelector("#mfNotice").textContent'),/constraint.*Input JSON/);
    const callsBefore=sent.length;await click('#mfRun');assert.equal(sent.length,callsBefore);assert.equal((await snapshot()).run,null);
    assert.equal((await snapshot()).batch.cases[0].expected_event_type,'constraint','removed labels are not rewritten');
    await click('#mfPaste');await setJSON({...customBatch,cases:customBatch.cases.map(c=>({...c,expected_event_type:'ignore'}))});await click('#mfLoad');
    await click('#mfRun');await wait('NorteMemoryPage.snapshot().run?.status==="done" && !NorteMemoryPage.isRunning()');
    assert.equal((await snapshot()).queues.memory.ignore.length,2);assert.equal((await snapshot()).queues.ignored.length,0);
    assert.equal(await evaluate('document.querySelector("#mfQueue-ignore").hidden'),true,'new categories default to collapsed');
    await click('[data-collapse="type:ignore"]');assert.equal(await evaluate('document.querySelector("#mfQueue-ignore").hidden'),false);
    await click('[data-collapse="type:ignore"]');assert.equal(await evaluate('document.querySelector("#mfQueue-ignore").hidden'),true);assert.equal(await evaluate('document.querySelector("#mfIgnoreQueue").hidden'),false);
    await click('#mfSaveTest');
    const many=JSON.parse(JSON.stringify(reduced));many.event_type.criteria=Object.fromEntries(['ignore','yes','no','input','risk / <new>','__proto__',...Array.from({length:6},(_,i)=>'category_'+i)].map(k=>[k,'Criterion '+k]));
    await saveQuestions(many);await click('#mfFit');await sleep(150);
    assert.equal(await evaluate('document.querySelectorAll(".mf-destination").length'),12);
    assert.equal(await evaluate('document.querySelectorAll("#mfDestinations new").length'),0,'custom labels are plain text');
    assert.ok(await evaluate('(()=>{const r=document.querySelector("#mfCanvas").getBoundingClientRect();return [...document.querySelectorAll(".mf-destination")].every(n=>{const b=n.getBoundingClientRect();return b.top>=r.top-1 && b.bottom<=r.bottom+1 && b.right<=r.right+1;});})()'),'all dynamic destinations fit within the canvas');
    await click('#mfCollapseAll');assert.equal(await evaluate('document.querySelectorAll("[data-collapse][aria-expanded=false]").length'),13);
    await click('#mfCollapseAll');assert.equal(await evaluate('document.querySelectorAll("[data-collapse][aria-expanded=false]").length'),0);
    // Tab indents the question textarea in-place without changing focus or autosaving.
    await click('#mfQuestions');
    const qBefore=await evaluate('document.querySelector("#mfQuestionJSON").value'),versionsBefore=(await snapshot()).library.versions.length;
    await evaluate('document.querySelector("#mfQuestionJSON").focus();document.querySelector("#mfQuestionJSON").setSelectionRange(2,2)');
    await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});
    assert.equal(await evaluate('document.activeElement.id'),'mfQuestionJSON');
    assert.equal(await evaluate('document.querySelector("#mfQuestionJSON").value'),qBefore.slice(0,2)+'  '+qBefore.slice(2));
    assert.equal((await snapshot()).library.versions.length,versionsBefore);await outside();
    const testsBeforeBrokenMemory=(await snapshot()).library.tests.length;
    await evaluate('localStorage.setItem("norte.meeting-memory.v1","{broken-checkpoint");window.beforeMemoryReload=true');
    await call('Page.reload');await wait('!window.beforeMemoryReload && window.NorteMemoryPage && NorteClassifier.isAvailable()');
    assert.match(await evaluate('document.querySelector("#mfNotice").textContent'),/registro original foi preservado/);
    await click('#mfRun');await wait('NorteMemoryPage.snapshot().run?.status==="done" && !NorteMemoryPage.isRunning()');
    assert.equal((await snapshot()).meeting_events.length,2,'a corrupt recovery checkpoint does not prevent in-memory classification');
    assert.equal(await evaluate('localStorage.getItem("norte.meeting-memory.v1")'),'{broken-checkpoint','never overwrite a corrupt checkpoint silently');
    assert.match(await evaluate('document.querySelector("#mfNotice").textContent'),/salve o teste/,'persistence failure remains visible after a run');
    assert.equal((await snapshot()).library.tests.length,testsBeforeBrokenMemory);
    await click('#mfSaveTest');assert.equal((await snapshot()).library.tests.length,testsBeforeBrokenMemory+1,'explicit archive save remains available');
    assert.equal(errors.length,0,JSON.stringify(errors));
    console.log('PASS: live meeting_events, configured raw FIFO, arrival timestamps, synchronized selection, persistent recovery, corruption safeguards, explicit test/version saves, old snapshots, dynamic categories, resizable panels and existing archive preserved. No paid calls.');
  }finally{socket?.close();chrome.kill('SIGTERM');server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
